# Generated by Django 4.1.4 on 2022-12-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment_comment_post_comment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_time',
            new_name='creation_time',
        ),
    ]
