# Generated by Django 4.1.4 on 2022-12-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_remove_post_creation_time_alter_post_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(default=None, upload_to='.uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='no title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='no body'),
        ),
    ]
